services:
  - type: web
    name: task-server
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"